### PR TITLE
Final bugfix on updating annotations

### PR DESCRIPTION
**Pull request by drew-sinha**
One more bugfix; didn't get this until the very end. Moved the updating annotations to process_experiment.segment_experiment (think it'll be cleaner anyways).

### CODE REVIEW

**Comment by zpincus** [comment]
Hmm, but this way if you use the lower level api to selectively segment just some images, the tcks don’t get updated. I think that’s closer to bug than feature? What do you think?

I’ll see if it’s easy to make the annotation updater run for a position dict rather than experiment dir...

**Comment by drew-sinha** [comment]
Fair point. Short answer: I think its equivocal right now. Long-term, I think the bugfix is closer to a better workflow.

If I'm using the low-level API, it's not guaranteed that I want to update the annotations. E.g. I want to benchmark a segmentation model on a new dataset that it hasn't seen before, or resegment old images with another model to see if I get a different result with analysis (like what I'm doing for autofluorescence). With the annotation updating in segment_positions, the low-level API is somewhat medium level. The ideal case for splitting segment_experiment vs segment_positions is where the big steps (segmentation and updating annotations) are decoupled. Then, segment_experiment explicilty delineates the default workflow that the lab subscribes to for run-of-the-mill segmentation. A user that wants to do something more complicated can model their workflow off segment_experiment.

In the same vein, I exposed the mask root for the low-level API on this last commit (it was already most of the way there in segment_images). That way, if one wants to do something more esoteric with segmentation, they aren't bound to dump everything into the default mask_root. Since so much of the standard workflow relies on 'derived_data/mask' containing the masks that one should care about for updating poses, the low-level API shouldn't necessarily fuss with that. One can then leave it to segment_experiments to default to the standard 'derived_data/mask' directory.

Does that seem reasonable?


________________________________

**Comment by drew-sinha** [comment]
Now that I'm thinking through this a little more, I'm kind of wary of the reliance of a default mask_root in the low-level API (segment_images:70-71). Should this be a positional argument? Then, segment_experiment can explicitly name this in the standard workflow....

**Comment by zpincus** [comment]
Good ideas all. I’m all for it! Thanks. 

Zach

**Comment by zpincus** [comment]
Check out e1973ae -- I think it addresses these concerns, and exposes rather more of the low-level logic for custom usage.

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

**Pull request merged**
